version: '3'
services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password # Dummy password for testing locally
      - MYSQL_DATABASE=todo 
    ports:
      - '3306:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  mariadb_data:

networks:
  mariadb:
    driver: bridge
